#!/usr/bin/env python3
"""
Serendipitous Oulipo Haiku Generator
Converts 418 first lines x 418 second lines x 418 third lines
into 73+ million possible haiku combinations
"""

import random
import json
from datetime import datetime
import os

# Your 418 haiku lines (abbreviated for space - you'll have the full arrays)
FIRST_LINES = [
                "serendipity",
                "sky sits on the ground",
                "a beautiful Run",
                "rain in the winter",
                "in my cup, coffee",
                "wake up to a hug",
                "winter sun gives hints",
                "hoya of Nana",
                "a foggy morning",
                "fog again today",
                "wind gusts bending trees",
                "teaching math all day",
                "swimming in a sea",
                "pentagonal life",
                "the silver lining",
                "my townsend warbler",
                "like a fluffy whip",
                "this path is flooded",
                "the base of thirteen",
                "why isn’t solstice",
                "paths beneath my feet",
                "crow grabs the sunlight",
                "faint little circle",
                "early morning song",
                "tip top, fir tree crow",
                "images within",
                "twisted growth, out, up",
                "look up — perspective",
                "beauty in my mind",
                "ribbons of fungus",
                "modest are the trees",
                "splashing in pure joy",
                "three generations",
                "black, soft, powder stick",
                "probability",
                "here, nested circles",
                "the various V’s",
                "yellow-rumped warbler",
                "together we play",
                "I always look up",
                "the lenses we have",
                "I breath in and out",
                "cumulative drops",
                "generosity",
                "the mind of a child",
                "ice rains down on life",
                "fire’s fingers dance,",
                "the parallel curves",
                "crow, quiet and still",
                "plot the Devil’s Curve",
                "lofty sequoia",
                "white smeared on the blue",
                "the death of my friends",
                "in just one moment",
                "the moment for tea",
                "repose beneath sky",
                "the delta, I am",
                "coding with patterns",
                "yellow river sky",
                "on the wire, one wire",
                "point under the sky",
                "council of the crows",
                "see the underneath",
                "the gurgling crows",
                "the seven of them",
                "oh, cedar waxwings",
                "pull that little string",
                "life shows its beauty",
                "I know you. my friend.",
                "lift yourself with breath",
                "just folding paper",
                "the sea leaves presents",
                "we architect webs",
                "I hugged my mother",
                "great white fawn lily",
                "even the strongest",
                "I am now learning",
                "a forest burned shows",
                "I am condensate",
                "those moments of pause",
                "I see reflection",
                "to be a raven",
                "vestiges of trees",
                "non-linear time",
                "the ease to forget",
                "trees churn with current",
                "walking random paths",
                "I have a fixed point",
                "I try to let storms",
                "abundance flowing",
                "trees dip their big toes",
                "lichen brings color",
                "a spiral beauty",
                "I have had to change",
                "a new path is found",
                "night time thoughts bring focus",
                "as a treehugger",
                "in an empty lot",
                "when you lean into",
                "I have a secret.",
                "like glaciers in spring",
                "you reach for the moon",
                "we are projections",
                "pappus chains; circles",
                "puddles of sunlight",
                "that forest fragrance",
                "tuck your babies in",
                "vortex of petals",
                "the swallows are here",
                "seeds we plant today",
                "happiness is now",
                "shadows can bring forth",
                "a tender wave wafts",
                "oh, fairyslipper",
                "I wish I knew how",
                "I was late for lunch",
                "cherry blossom swirls",
                "you must bury things",
                "light offers shadows",
                "sometimes it’s the clouds",
                "when is it, you ask",
                "seek out your zeros",
                "gratitude sneaks up",
                "a swallow ballet",
                "just a breath away",
                "be the blank canvas",
                "we live in these loops",
                "an insane loudness",
                "your feet hold freedom",
                "the weight of a cloud",
                "we all can transform",
                "the outline of death",
                "the fractals of us",
                "I feel this blanket",
                "tell me where to stand",
                "you are potential",
                "the most precious things",
                "solve the soma cube",
                "determination",
                "and when you suffer",
                "cedar waxwings flock",
                "window deja vu",
                "you turn towards the light",
                "so many creatures",
                "I wished to see moon",
                "plan those garden beds",
                "ink can be messy",
                "unfold at sunrise",
                "I saw the sunrise",
                "sometimes birdwatching",
                "pondering polar",
                "He has a paintbrush",
                "you can let go now",
                "you still have that dream",
                "dynamic systems",
                "what once brought me joy",
                "we perch at the top",
                "with no dimension",
                "love gutter bubbles",
                "I just glimpsed the light",
                "you ensure the life",
                "you gather to speak",
                "play brings character",
                "the forget-me-nots",
                "you were in my hands",
                "our feathers tell us",
                "see generations",
                "do we flock like Boids?",
                "you do amaze me",
                "baby nuthatches",
                "when I am running",
                "my orchid’s face me",
                "a vortex caught me",
                "long shadows pull me",
                "a Fermat spiral",
                "gossamer catches",
                "revert to a child",
                "my Nana does speak",
                "I see you, right there",
                "immerse all of you",
                "who would have thought that",
                "let us hold it all",
                "I feel all the strands",
                "squeeze through the portal",
                "sometimes do you feel",
                "ducklings form a mass",
                "bees bring such a joy",
                "perspectives give us",
                "in a full orbit",
                "like the heat bubble",
                "when between two rocks",
                "fractions of flowers",
                "ocean sand ridges",
                "she removes her veil",
                "heart rate integrals",
                "strands of life do hang",
                "this year you have bloomed",
                "you chase in the tree",
                "you taught me the words",
                "on my forest runs",
                "look closely on trails",
                "the simplest joy",
                "butterfly vortex",
                "the color palettes",
                "evening clouds whisper",
                "a beautiful gift",
                "when I’m dead and gone",
                "“it’s the hill your on”",
                "self portraits are tough",
                "three-hundred-sixty",
                "hello my deer friend",
                "my mind ebbs and flows",
                "geometric egg",
                "this isolation",
                "I am to math art",
                "precious gems exist",
                "there is a pulse here",
                "simple churns of thought",
                "fractal streams draw me",
                "all tracks in your life",
                "I stumbled upon",
                "I found a carcass",
                "I long for language",
                "gaze in reflection",
                "time; non-linear",
                "a simplicity",
                "sometimes your anthers",
                "your presence brings joy",
                "sunflowers bow their",
                "light seems to find you",
                "good morning my friend",
                "I know what you are!",
                "parabolic curves",
                "there’s this ritual",
                "cottonwoods have arms",
                "sometimes we muster",
                "laying on my back",
                "brace yourself here; now",
                "but I feel as if",
                "our days are fractals",
                "how the light alone",
                "I see you peeking",
                "untangling this mess",
                "maybe all our days",
                "selflessness is just",
                "I am so grateful",
                "I know that my friends",
                "there are just some trails",
                "you asked permission",
                "slough of quietude",
                "I was on my run",
                "there are these paintings",
                "this hug was intense",
                "I could walk this path",
                "do you like to think",
                "you know you must go",
                "I know, even though",
                "in the corner you",
                "sometimes luminance",
                "in the quiet dusk",
                "even the clouds long",
                "some of us are those",
                "such perfection is",
                "you swept over me",
                "there are these days — times",
                "oh my! look at you",
                "I breathed alder air",
                "when you turn in a",
                "sometimes you just run",
                "there are days in which",
                "you gather yourself",
                "the weight that you lift",
                "to feel that soft breeze",
                "sine waves in the clouds",
                "when I banished you",
                "sustenance I made",
                "you just know how to",
                "I long for rivers",
                "you have this structure",
                "our lens can turn us",
                "at the tops of hills",
                "I dream that you kiss",
                "so precious is now",
                "autumn calls us all",
                "do you ever just",
                "symmetry of days",
                "tiny little life",
                "sunlight in canyons",
                "I see your columns",
                "let yourself be here",
                "our consciousness is",
                "when you submerge, keep",
                "in the mossy dusk",
                "your palm faces down",
                "sometimes you long to",
                "hello my winged friend",
                "my cedar waxwing",
                "my home has a guard",
                "soak in your warm bath",
                "we are all so close",
                "the most open paths",
                "oh, yes, this is it!",
                "you root yourself deep",
                "my luck dragon came",
                "we run the same paths",
                "some of these rivers",
                "I treat my tea bag",
                "this colorful mist",
                "however I tread",
                "your entire self — world",
                "oh my bald cypress",
                "sometimes it’s the clouds",
                "you gather right there",
                "The structure of you",
                "it is like you stand",
                "I saw you today",
                "I picture myself",
                "stopped my class today",
                "I write this for you",
                "your consistency",
                "I found you — fallen",
                "I keep company",
                "I could write more than",
                "reflections at sea",
                "a puddle can seem",
                "just look at you there",
                "you need solitude",
                "you are a symbol",
                "you reach down into",
                "we all need this path",
                "I think that you might",
                "I need to walk there",
                "you just might feel it",
                "Cassiopeia",
                "in the sky — a sign",
                "this night sky that comes",
                "little winter bee",
                "we all cling sometimes",
                "my road is the path",
                "as you look down here",
                "you take off and fly",
                "there are these comets",
                "even planets, stars",
                "you’re my paradox",
                "oh, oyster catcher",
                "a light of guidance",
                "the clouds and the sea",
                "there exists nothing",
                "just make sure that you",
                "be the horizon",
                "I see sentinels",
                "dive deep into waves",
                "I saw the blue mass",
                "a vector on wind",
                "imagine being",
                "so many curves here",
                "grab the sky and loam",
                "dim the light with fog",
                "to connect with you",
                "the muddy puddles",
                "your little footprints",
                "a flurry of white",
                "you anticipate",
                "there you are, my hawk",
                "your path can be framed",
                "some windows are but",
                "I glanced at you — there",
                "oh, how you long to",
                "generative art",
                "a forest of ferns",
                "sitka my sitka",
                "when you miss the moon",
                "the elk must have left",
                "bubbles have been packed",
                "you harbor beauty",
                "an aperture formed",
                "somehow blooms do form",
                "it’s best not to see",
                "the currents of geese",
                "just for a moment",
                "get ready for night",
                "breadcrumbs of sunbeams",
                "companion within",
                "a tide of forest",
                "even in our death",
                "what seems like chaos",
                "I think that you must",
                "could this day just be",
                "shoes of sand and moss",
                "now, lessen yourself",
                "your life has texture",
                "you play when hidden",
                "shadows stretch across",
                "separate you stand",
                "I see this window",
                "reminders of love",
                "little hummingbird",
                "thank you my river",
                "I feel the evening",
                "messengers of trees",
                "you drape down – from up",
                "the most shadowed trail",
                "there are these night skies",
                "Earth has silhouettes",
                "sing to the kitties",
                "this junction of ray",
                "I know this portal",
                "I am sorry friend",
                "thirty little squares",
                "so, obviously",
                "you have the widest",
                "this small white primrose",
                "I folded this crane",
                "on a walkabout",
                "your little hands here",
                "when you are present",
                "there is no limit",
                "and so, here I am",
              ]

SECOND_LINES = [
                 "of serendipity in",
                 "contained within the puddles",
                 "crows in puddles and in trees",
                 "closest to the sun today",
                 "smell, taste of being awake",
                 "pink Clouds wrap around my eyes",
                 "like a love note in the morn",
                 "generations green and full",
                 "faint branches in a white sea",
                 "the same and yet different",
                 "hummingbird stands firm and still",
                 "sine, cosine, tangents and more",
                 "droplets, the bubbles in air",
                 "perfect, beautiful flowers",
                 "orchid blooming for a year",
                 "yellow streaks in my backyard",
                 "but chaotic and angry",
                 "with a moment — reflection",
                 "would be an interesting",
                 "the year’s end or beginning",
                 "nodes in the past and future",
                 "warmth catching the top branches",
                 "partially obscured by sky",
                 "vibrato pierces the morn",
                 "claim the branch, caw to below",
                 "vivid inner gratitude",
                 "holding sky with tangled limbs",
                 "cedars converge together",
                 "look inwards with boundlessness",
                 "gossamer laced water beads",
                 "moss draping over branches",
                 "immersing in the moment",
                 "together, watching the birds",
                 "the raw transforms to beauty",
                 "crows checking under each leaf",
                 "ripples from raindrops expand",
                 "configurations of flight",
                 "flit, fly, jump, play — pierce the gray",
                 "such precious time in this life",
                 "to the trees; magnificent",
                 "magnify, distort, and bend",
                 "the air that circles the earth",
                 "glazing ice on leaf and limb",
                 "so humbling, loving, and kind",
                 "creative, curious, joy",
                 "smoothing bumps, magnifying",
                 "wrap and hug life that once was",
                 "encasing sedum in ice",
                 "waits, watches, ruffles, then flies",
                 "center on infinity",
                 "reach, spread your canopy",
                 "hints of orange and purple",
                 "I felt the ground shake all night",
                 "a head injury, a loss",
                 "remove leafs at the right time",
                 "find the space within your mind",
                 "changing, growing, condensing",
                 "knit, purl, yarn over, and slip",
                 "in fall you came, but no more",
                 "one crow sits; a single Om",
                 "vector fields of stick and cloth",
                 "rupture with flight and chorus",
                 "the silhouettes of anthers",
                 "to each other, back and forth",
                 "together in flight and tree",
                 "gulping berries at sun set",
                 "that will lead you down that path",
                 "the tiny details abound",
                 "still budding though you lay down",
                 "in and out of your being",
                 "creates dragon curve beauty",
                 "precious tokens, and small hints",
                 "strands of kindness, grace, and love",
                 "I embraced every moment",
                 "looking down, your tender roots",
                 "will become covered with moss",
                 "how to play, to be a child",
                 "the skeletal curvature",
                 "dew that has settled on life",
                 "bring brown creepers to focus",
                 "homeomorphic tree tops",
                 "to play in the winds of life",
                 "swept away — a tide of men",
                 "you are like honey and light",
                 "that we are but on a speck",
                 "rooted, wooden, in whirlpools",
                 "looking for meaning, we see",
                 "but my distance grows in time",
                 "blow through me and around me",
                 "my vessel is full of life",
                 "into the streams of the sky",
                 "composite life of crutose",
                 "rotational symmetry",
                 "change my radius of thought",
                 "it was always here — ready",
                 "moonlit branches projected",
                 "plant me beside, beneath one",
                 "between the houses, hidden",
                 "that mountain ahead; summit;",
                 "when overwhelmed with beauty,",
                 "chaffing ice in the sun’s warmth",
                 "your little arms, unaware",
                 "of all in the past/future",
                 "pack them like bijou trinkets",
                 "scintillate with the soft breeze",
                 "of moss, earth, stream, trees, and life",
                 "with bits of pollen and mud",
                 "come to hold my hand, farewell",
                 "dancing in erratic flight",
                 "may bring forth fruits beyond us",
                 "breathe it, let it permeate",
                 "awareness of light; contrast;",
                 "through my entire being",
                 "so delicate and hidden",
                 "to comfort devastation",
                 "hummingbird stopped me to talk",
                 "turbulence with breath, movement",
                 "before you can grow; anew",
                 "the silhouettes that reveal",
                 "that provide us with brilliance",
                 "the negative space becomes",
                 "those intersections in self",
                 "in quite moments of breath",
                 "swooping, dancing, and diving",
                 "from an utter nakedness",
                 "that calls for all the pigments",
                 "mandalas of all our time",
                 "silences itself only",
                 "to run, prance through life’s meadows,",
                 "immense, vast, ocean of mist",
                 "translate, reflect, rotate and",
                 "struck down by the weight of ice",
                 "better plotted in polar",
                 "that wraps me in warmth and love",
                 "and I will love every",
                 "a ball of a peony",
                 "found without expectation",
                 "puzzle possibilities",
                 "origami creases you",
                 "take a breath and do something",
                 "sipping dew of torch lilies",
                 "little hummingbirds come, go.",
                 "that setting sun, warm your breast",
                 "settle down in the long light",
                 "but I was deeply shrouded",
                 "but let those volunteers grow",
                 "painting the world in contrast",
                 "chaotic origami",
                 "within a rose’s petals",
                 "in the reeds of a refuge",
                 "distance and angle of me",
                 "that feathers the clouds above",
                 "release the grip that it has",
                 "of flight above all of it",
                 "within your life bring chaos",
                 "has become an impetus",
                 "on dead branches among clouds",
                 "you can be a single point",
                 "perfect hemispheres reflect",
                 "another reality",
                 "that surrounds us all, will grow",
                 "together like wolves that howl",
                 "and the unexpected joy",
                 "are now weeks past their season",
                 "tiny feet, before you died",
                 "stories of chases, of flight",
                 "in one sedum, young to old",
                 "cohesion yet separate",
                 "finding your way without sight",
                 "quivering with their cuteness",
                 "I do feel incredibly free",
                 "maybe all flowers do this",
                 "I was enmeshed in spirals",
                 "from any doubt or sadness",
                 "lured me from my dreams last night",
                 "the light of the sun and moon",
                 "and savor those ripe berries",
                 "from the evening robins’ beaks",
                 "beneath the trees, sun, and moon",
                 "into the day’s sublime blooms",
                 "flowers’ beauty marks exist?",
                 "the weight gives way for the light",
                 "there’s hundreds of finish lines",
                 "between points into a void",
                 "like folded origami?",
                 "of little feathers and down",
                 "gardens smile at their presence",
                 "a way to see each other",
                 "our view is from a plane, yet",
                 "I feel their anxiety",
                 "lift into the sky above",
                 "stretch out from golden circles",
                 "paint the histories of tides",
                 "revealing ancient forest",
                 "could sum the beats of a life",
                 "in helical curls catching",
                 "to remind me of your laugh,",
                 "you yell and fight over it",
                 "moments learning the flowers",
                 "accidental flushing dog",
                 "for the hidden forest doors",
                 "of dancing curves of sunshine",
                 "flutters and swirls before me",
                 "of an origami quilt",
                 "of the day, of tomorrow",
                 "to sit and watch little swifts",
                 "the best gift I could give you",
                 "absolutely wonderful",
                 "that’s why we should all do them",
                 "is still such a limited",
                 "shall we prance along this path",
                 "without the dry spells, the flood",
                 "constructed with four circles",
                 "brings on creativity",
                 "as a Bee is to flower",
                 "at the junction. Sand and sea.",
                 "you can feel it at the edge",
                 "lead us to the mind’s wonders",
                 "to a gratitude’s ocean",
                 "will be erased by time’s tides",
                 "the most beautiful pattern",
                 "half buried in sand ripples",
                 "to speak with the universe",
                 "at your beauty, your being",
                 "brings us through our existence",
                 "in plucking sprigs of currants",
                 "just need to reach higher up",
                 "come and sit with me; this day",
                 "heavy heads in reverence",
                 "reflecting from this good earth",
                 "you peek over the grapes to",
                 "catching the little white moths",
                 "appear on my walkabouts",
                 "of warm coffee in my cup,",
                 "that hug me; sitting so small",
                 "another bloom; another",
                 "on the forest floor — I feel",
                 "for this — the ground shaking breath",
                 "I fly with all of them that",
                 "the sun rises and then sets",
                 "can make the same daily path",
                 "from behind those purple clouds",
                 "makes me feel like a kitten",
                 "are but loops in the garment",
                 "what this small, precious world needs;",
                 "for all of the abundance",
                 "will flip the leaves from my grave",
                 "that draw you in; and call you",
                 "but then just came anyway",
                 "let me sit at your still side",
                 "you tripped me, floating there. but",
                 "with strokes of grass and azure",
                 "it left only a small crack",
                 "and dip myself in the clouds",
                 "about all your vertices",
                 "float away on gentle breeze",
                 "you need not the sun or moon",
                 "tease me with the gold to come",
                 "lets us forget what it is",
                 "you savor the wind and light",
                 "to caress you and your light",
                 "that practice the art of firm",
                 "found in every little",
                 "just to remind me, nudge me,",
                 "that I can hardly breathe — gasp",
                 "my precious chickadee-dee",
                 "it filled my lungs with quiet",
                 "certain way, the sky swallows",
                 "straight into a wall of life",
                 "a palette knife smears serpents",
                 "to look at the different",
                 "to the heights that you take wing",
                 "as you come to repose — pause",
                 "curve down the spine of our sky",
                 "your response — absolutely",
                 "for you, was an act of love",
                 "immerse me in your language",
                 "with their agates and whirlpools",
                 "that you store your quietness",
                 "our world —an upside down sphere",
                 "your calls and antics amuse",
                 "asymptote, vanishing point",
                 "with youthful minds in my home",
                 "just the other day, grape leaves",
                 "look deep at your reflection",
                 "rotational — reflective",
                 "on the floor of the forest",
                 "forges clouds among the trees",
                 "extensions of my being",
                 "in your autumn glow, right now",
                 "but drops — collecting, dripping",
                 "your eyes wide open to see",
                 "reflect your being in the",
                 "to feel this — a precious earth",
                 "cross a bridge from the beneath",
                 "I see you and your colors",
                 "fill yourself with this bounty",
                 "a battle-ready sentry",
                 "get lost in thought and dream big",
                 "to the heights that we desire",
                 "may be the wettest or tough",
                 "completely immerse yourself",
                 "while reaching over a stream",
                 "to remind me — dream of sky",
                 "and yet we experience",
                 "swiftly move with such volume",
                 "like it is the very last",
                 "brings me in and out of the",
                 "may it be quiet and soft",
                 "is but a dew drop of sky,",
                 "you have shed for the season",
                 "that provide the light you seek",
                 "ready to coalesce — one",
                 "is beyond understanding",
                 "always reaching to the west",
                 "in the window made by rain",
                 "merging with the trees and leaves",
                 "so they could all see this bird",
                 "a permission slip to be",
                 "does humble me to this earth",
                 "glorious touching the earth",
                 "that demands sugary treats",
                 "a thousand poems of you",
                 "lead you to this perspective",
                 "to be a portal of sky",
                 "playing in the waves, currents,",
                 "to truly reflect on you",
                 "for being steadfast, constant",
                 "the depths of the light and dark",
                 "a trail to be hopped and skipped",
                 "reach with your iterations",
                 "in that space — sans time — sans thought",
                 "an ancient forest of life",
                 "hello — I can see you now",
                 "greater than Saturn — painted",
                 "earlier now. Lets us know",
                 "on the rosemary and frost",
                 "to a season that has passed",
                 "of light and shadow, those lines",
                 "at the leaves that you have lost",
                 "when the wind whispers to you",
                 "that have tails pointing ahead",
                 "can become tangled in lines",
                 "coastline measured by atom",
                 "do seek out that which blends in",
                 "does not point its beam at you",
                 "pull me to that single point",
                 "like the sound of waves pulling",
                 "seize those moments that make you",
                 "grab the celestial light",
                 "they guard their posts — stand ready",
                 "and find they are but water",
                 "of this precious blue planet",
                 "with the magnitude of life",
                 "that crest of water — a wave",
                 "arcs of me, of time — being",
                 "place them in your mind’s pocket",
                 "so you can hear the whispers",
                 "I will reach with all my time",
                 "can reflect heavenly light",
                 "fill my soul with joy,love. In",
                 "swirls in your radiant light",
                 "that your trail will not be full",
                 "contemplating reflection",
                 "with the steel beams of your thoughts",
                 "fractals into more windows",
                 "an impetus for your flight",
                 "break free from these tangled limbs",
                 "in the cracks beneath my feet",
                 "upon a forest by sea",
                 "shelter me with your branches",
                 "just keep going — it is but",
                 "just before this headland warmed",
                 "on the surface of the depths",
                 "in your layers as they fall",
                 "to manifest silver clouds",
                 "from life that I did not know",
                 "too far ahead of your path",
                 "flow through the ocean of sky",
                 "I thought you might sit with me",
                 "to journey beneath the stars",
                 "lead you to the horizon",
                 "together in solitude",
                 "echoes with branches in streams",
                 "we may spring forth foliage",
                 "might be — organized — perfect",
                 "run your fingers through this sand",
                 "painted for you — offering",
                 "cushion your steps as you run",
                 "below the grasses of thought",
                 "of earth and aether — of self",
                 "converse in intimate joy",
                 "the dunes of me — parallel",
                 "in an ocean of currents",
                 "it appears, just at my feet",
                 "sprout from every atom",
                 "be the leaf on winter’s tree",
                 "for receding from my path",
                 "approach ing— and yet you’re here",
                 "whisper of white oaks and fir",
                 "almost as if you desire",
                 "will still have footsteps of light",
                 "that make you feel like you’re on",
                 "infinite, ever-changing",
                 "when you enter the forest",
                 "and your fractal being – now",
                 "locked within is history",
                 "that you stand alone out here",
                 "make this icosahedron",
                 "you have been trained to lure us",
                 "reach with those ancient branches",
                 "whispered to my deepest self",
                 "to put a thought of peace here",
                 "pause to see the warp and weft",
                 "hold what is precious and clear",
                 "ev’ryone becomes silent",
                 "for the number of poems",
                 "in the rain beneath this sky",
               ]

THIRD_LINES = [
                "serendipity",
                "clouds splash on my feet",
                "watch me; smile at me",
                "hide aphelion",
                "today, good morning!",
                "good morning Glory",
                "I glow in the warmth",
                "blooming in my sill",
                "like old memories",
                "fractal winter days",
                "strength in this small life",
                "it is my function",
                "fog rolls in like tide",
                "beauty does abound",
                "beauty in my home",
                "a glow in winter",
                "the squirrel tail scolds",
                "to then turn around",
                "thought our units",
                "are we not of space?",
                "graphs of my being",
                "black feathers at dusk",
                "branches reach, yearning",
                "birds rouse the whole earth",
                "announce the sunset",
                "a place to gather",
                "silhouette white oak",
                "whispering of blue",
                "uncountable, be",
                "life’s intricacies",
                "hidden is the wood",
                "in the now of life",
                "quiet etched in time",
                "charcoal to paper",
                "p of finding nuts",
                "glitches in water",
                "absolute values",
                "harbinger of spring",
                "learning quarantunes",
                "my smallness is known",
                "our reality",
                "the eddies of life",
                "winter steps on spring",
                "loving thy neighbor",
                "never let yours go",
                "winter chandeliers",
                "air, to tree, to air",
                "small bubbly fractals",
                "through the moon’s dim light",
                "lemniscate in walls",
                "envelope my eyes",
                "clouds gather to speak",
                "you lay cleft at dawn",
                "never in silence",
                "as with all life’s gifts",
                "clear the clouds of thought",
                "into me, not me",
                "for loops in the wool",
                "tributaries — gone",
                "resonant with us",
                "show her vortices",
                "choices have been made",
                "are manifested",
                "what poems they speak",
                "an aerie of grace",
                "you bring me such joy",
                "a trail for thinking",
                "within all of this",
                "cherish these last leaves",
                "a moment will do",
                "spirals of corners",
                "from a hidden world",
                "parametric us",
                "we have ever had",
                "beneath your breath — “spring”",
                "when alone with time",
                "play means letting go",
                "flesh removed from earth",
                "destined for the soil",
                "camouflage now seen",
                "painted in puddles",
                "closer to the light",
                "only roots remain",
                "a trickle, a gush",
                "in a universe",
                "centuries of flow",
                "pareidolia",
                "evolving conchoid",
                "but, sometimes I break",
                "when I am present",
                "manifest eddies",
                "a vibrant puddle",
                "perfection in life",
                "to find happiness",
                "now realized and walked",
                "vivid silouettes",
                "the ultimate hug",
                "pocket of lilies",
                "spread your arms and fly",
                "my soul blows kisses",
                "tulips melt petals",
                "of that great distance",
                "the shadows today",
                "memories’ bubbles",
                "ablutions from sky",
                "lingers deep inside",
                "lullaby buzzing",
                "white gives way to green",
                "then they perch, so still",
                "propagating good",
                "ev’ry living cell",
                "reveal gratitude",
                "I awake in grace",
                "a precious orchid",
                "it can feel hopeless",
                "of the kale flowers",
                "what currents we make",
                "life is letting go",
                "orientation",
                "wispy tufts of grace",
                "positive? a shift",
                "ready to be filled",
                "the awe of it all",
                "violet, green flight",
                "revealing true form",
                "evolve into art",
                "living in circles",
                "at the ocean’s edge",
                "paths, trails of wonder",
                "catches the sun’s rays",
                "we even dilate",
                "the remnants of life",
                "days, loops, through the years",
                "everywhere I go",
                "iota of earth",
                "preparing to bloom",
                "on the forest floor",
                "and create you own",
                "fall into the fold",
                "utterly selfless",
                "a painted earful",
                "fly, eat, then repeat",
                "at the tops of trees",
                "evening prayers",
                "in a cloud of sleep",
                "the spring surprises",
                "spilled to inspire change",
                "turning in at night",
                "warmth from radiance",
                "you see a chicken",
                "to what reference?",
                "into reminders",
                "detach and then breathe",
                "to feel the cloud’s breath",
                "absolute beauty",
                "ringing in my head",
                "so we can perceive",
                "to be a focus",
                "they show us the sky",
                "shining through the ground",
                "with grains of pollen",
                "in waves of cawing",
                "to the norms of life",
                "brightening shadows",
                "little chickadee",
                "ruffles in our time",
                "in growth together",
                "and staying aligned",
                "holding tight; reaching",
                "sit now before me",
                "to dwell within me",
                "the ones that I see",
                "on the forest floor",
                "to the long light rays",
                "thoughts wrapped around me",
                "and then scintillates",
                "crouched in the garden",
                "singing of glory",
                "ready to unfurl",
                "utter abundance",
                "pulchritudinous",
                "contrast is but life",
                "across our life’s trails",
                "with the deltoid curve",
                "relax your creases",
                "trailing a mother",
                "transforming in growth",
                "hope for unity",
                "like a point in space",
                "dreading suffering",
                "with all of your heart",
                "Pisano petals",
                "and then sweep away",
                "vestige roots of time",
                "critical moments",
                "filtered solar light",
                "smile, and hands. Nana",
                "that small piece of moss",
                "an umbellifer",
                "birds flit from my path",
                "that lead to wonder",
                "in my coffee cup",
                "I want to fly in",
                "are much to ponder",
                "of this time right now",
                "ajar to the world",
                "is to leave no trace",
                "when you get to peak",
                "mirrors for inside",
                "view of this wonder",
                "and chase swallowtail?",
                "of thought means nothing",
                "together a seed",
                "quintessence being",
                "covered in passion",
                "at the oceans breath",
                "of your consciousness",
                "make a space for this",
                "one drop fills my soul",
                "yet, still tread lightly",
                "written by water",
                "hundreds of years old",
                "in a silent mind",
                "drink it into you",
                "to be here and now",
                "listening to birds",
                "out of your flower",
                "in my green garden",
                "to the summers end",
                "to your inner self",
                "wake me from slumber",
                "western wood-peewee",
                "life’s concavity",
                "listening to birds",
                "at their solemn feet",
                "shoot; despite ourselves",
                "I hear, I exist",
                "that you are given",
                "have ever loved me",
                "until it doesn’t",
                "so wondrously new",
                "you — vast and beyond",
                "completing a proof",
                "we create in life",
                "breathe out compassion",
                "in this existence",
                "looking for treasure",
                "to the stream; ocean",
                "prior to response",
                "and breath in this life",
                "with help you took off",
                "that still my being",
                "between our essence",
                "boardwalk to the sky",
                "and edges within?",
                "to start to become",
                "that you still love them",
                "raining from the sky",
                "that is up or down",
                "as pink fades to night",
                "wrapping around beams",
                "and serious fun",
                "iota of life",
                "to look up — skyward",
                "due to gratitude",
                "just beaming with joy",
                "spores of seasons’ growth",
                "you — your silhouette",
                "it embraces you",
                "on the azure sky",
                "versions you can be",
                "don’t go unnoticed",
                "is a bounty breathed",
                "a slow dance of white",
                "astonishing — bloom",
                "your smile — a delight",
                "of branches and roots",
                "places for quiet",
                "to keep it secure",
                "is there really up?",
                "my canada jay",
                "pulls you together",
                "leaving playful trails",
                "danced in the changed wind",
                "in awe we exist",
                "nodes of our time here",
                "calls me to be small",
                "breath in this wildwood",
                "reaching skyward — up",
                "a light before dark",
                "evaporating",
                "all that flows in time",
                "selfless river here",
                "a nurturing act",
                "to get your feet wet",
                "joyful perfection",
                "I grew it for you",
                "hummingbird defense",
                "reflect and renew",
                "just remove the load",
                "but they will have light",
                "in the day’s raindrops",
                "of utter delight",
                "all that is above",
                "such different days",
                "depth has no meaning",
                "tied for each refill",
                "focus of this path",
                "as though I am not",
                "clay, and ev’rything",
                "now, take in more light",
                "in dark winter days",
                "puddle of raindrops",
                "beautiful — complex",
                "waiting for sunset",
                "whispering of love",
                "not just in shadow",
                "summer tanager",
                "the person you are",
                "a night reflection",
                "while reflecting sky",
                "and announces life",
                "and still fall so short",
                "earth and sky as one",
                "cradled by the Earth",
                "and eddies of life",
                "at the lowest tide",
                "no matter the seas",
                "to root yourself in",
                "to bring us to youth",
                "for a sunlit hug",
                "to truly exist",
                "that is now but grass",
                "as the last leaves fall",
                "as the darkness came",
                "our place in the stars",
                "gather energy",
                "not ready to go",
                "in the winter sun",
                "remember the sky",
                "that it is now time",
                "to the vast beyond",
                "of aether and light",
                "finite — infinite",
                "bring us forth those pearls",
                "instead, it drops hints",
                "a focus within",
                "cobbles at high tide",
                "utterly alive",
                "at your ocean’s edge",
                "in hopes of french fries",
                "connected to Earth",
                "leap up to kiss sky",
                "direction of change",
                "that just catches light",
                "the universe rounds",
                "to have them always",
                "of what surrounds you",
                "for it’s what I have",
                "you just have to look",
                "this brief existence",
                "calling you to dance",
                "of water and ducks",
                "in this little pond",
                "to bridge within you",
                "iterated views",
                "to gossip of this",
                "to be swept by wind",
                "ever evolving",
                "modest are the trees",
                "as I lean to you",
                "a sign on your way",
                "with the morning’s grace",
                "of my consciousness",
                "off of you in age",
                "at the lowest point",
                "was so capable",
                "look at what’s in reach",
                "bringing waves of north",
                "and talk of the birds",
                "unconstrained by thought",
                "of an inner light",
                "at the shore of soul",
                "temporal beings",
                "out of what remains",
                "beyond what we grasp",
                "to find what is deep",
                "a breath of color",
                "joyfully alive",
                "be in quiet awe",
                "and empty of self",
                "‘fore you fly away",
                "conforming to curve",
                "glorious — alone",
                "of another Earth",
                "of this universe",
                "and sing of the spring",
                "so that I may flow",
                "to tuck me in — dream",
                "of growth and decay",
                "heaven and the Earth",
                "contrast on our path",
                "another planet",
                "possibilities",
                "that stands still and dark",
                "goes – as you orbit",
                "I have passed this past",
                "I will sit with you",
                "origami joy",
                "with your fluff and stance",
                "forest holding hands",
                "of growth beneath soil",
                "and then held my breath",
                "of life around you",
                "to the morning beams",
                "until you take flight",
                "to this small flower",
                "drops encompass me",
              ]

def generate_haiku():
    """Generate a random haiku from the 418^3 combinations"""
    n = len(FIRST_LINES) - 1

    l1 = random.randint(0, n)
    l2 = random.randint(0, n)
    l3 = random.randint(0, n)

    haiku_content = f"{FIRST_LINES[l1]}\n{SECOND_LINES[l2]}\n{THIRD_LINES[l3]}"

    return {
        'content': haiku_content,
        'date': datetime.now().isoformat(timespec='milliseconds') + 'Z'
    }

def save_current_haiku(haiku):
    """Save the current haiku to current_haiku.txt"""
    with open('current_haiku.txt', 'w', encoding='utf-8') as f:
        f.write(haiku['content'])

    return haiku

def save_to_poems_json(haiku):
    """Add new haiku to the growing poems.json collection"""
    # Fix the path - go up one directory from scripts/ to find data/
    poems_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'poems.json')

    try:
        with open(poems_path, 'r', encoding='utf-8') as f:
            poems = json.load(f)
    except FileNotFoundError:
        # Create data directory if it doesn't exist
        os.makedirs(os.path.dirname(poems_path), exist_ok=True)
        poems = []

    # Add new haiku to the beginning (most recent first)
    poems.insert(0, {
        'content': haiku['content'],
        'date': datetime.now().isoformat(timespec='milliseconds') + 'Z'
    })

    # Save back to the correct path
    with open(poems_path, 'w', encoding='utf-8') as f:
        json.dump(poems, f, indent=2)

    return poems

def main():
    """Generate and save a new haiku"""
    # Generate new haiku
    haiku = generate_haiku()

    # Save to current_haiku.txt
    save_current_haiku(haiku)

    # Add to poems.json archive
    poems = save_to_poems_json(haiku)

    # Print for verification
    print("Generated new haiku:")
    print(haiku['content'])
    print(f"Generated at: {haiku['date']}")
    print(f"Total poems in archive: {len(poems)}")
    

    return haiku

if __name__ == "__main__":
    main()